# Generated by Django 3.2 on 2023-12-10 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимые символы в slug!!!', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимые символы в slug!!!', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Идентификатор'),
        ),
    ]
